#!/bin/bash

cd `dirname $0`

{
    echo "// autogenerated by rethemendex.sh"

    find . \! \( -path ./themes -prune \) -iname _\*.scss |
        fgrep -v _components.scss | LC_ALL=C sort |
        while read i; do
            echo "@import \"$i\";"
        done
} > _components.scss
