- name: "A-Aliases"
  color: "bfd4f2"
- name: "A-Authentication"
  color: "bfd4f2"
- name: "A-Autocomplete"
  color: "bfd4f2"
- name: "A-Breadcrumbs"
  color: "bfd4f2"
- name: "A-Bridge"
  color: "bfd4f2"
- name: "A-Broadcast"
  description: "Broadcast-style voice messages"
  color: "bfd4f2"
- name: "A-Create-Room"
  description: "Create room flow, user suggestions, etc."
  color: "bfd4f2"
- name: "A-DevTools"
  description: "/devtools, show hidden events, etc."
  color: "bfd4f2"
- name: "A-Dialogs"
  color: "bfd4f2"
- name: "A-Disambiguation"
  color: "bfd4f2"
- name: "A-DM-Start"
  description: "Creating a DM with another user"
  color: "bfd4f2"
- name: "A-E2EE-Dehydration"
  color: "8CC59A"
- name: "A-Electron"
  color: "bfd4f2"
- name: "A-Element-Call"
  description: "Group calls via Element Call"
  color: "bfd4f2"
- name: "A-Element-R"
  description: "Issues affecting the port of Element's crypto layer to Rust"
  color: "bfd4f2"
- name: "A-ELS"
  description: "Event List Summary (and Membership ELS, MELS)"
  color: "bfd4f2"
- name: "A-Emotes"
  color: "bfd4f2"
- name: "A-EMS"
  description: "Issues related to EMS"
  color: "bfd4f2"
- name: "A-Error-Message"
  color: "bfd4f2"
- name: "A-Federation"
  color: "bfd4f2"
- name: "A-Feedback-Reporting"
  description: "Reporting process for bugs, debug logs (rageshakes), suggestions"
  color: "bfd4f2"
- name: "A-File-Download"
  color: "bfd4f2"
- name: "A-File-Panel"
  color: "bfd4f2"
- name: "A-Identity-Server"
  color: "bfd4f2"
- name: "A-Indexing"
  description: "Indexing messages via Seshat"
  color: "bfd4f2"
- name: "A-IRC-Layout"
  color: "bfd4f2"
- name: "A-Jump-To-Date"
  description: "Jump to date headers or slash command"
  color: "bfd4f2"
- name: "A-Lazy-Loading"
  color: "bfd4f2"
- name: "A-Light-Box"
  description: "UI when viewing an image"
  color: "bfd4f2"
- name: "A-Location-Sharing"
  color: "bfd4f2"
- name: "A-Logout"
  description: "Logout, sign out, etc."
  color: "bfd4f2"
- name: "A-Maths"
  description: "Render LaTeX maths in messages"
  color: "bfd4f2"
- name: "A-Memory"
  description: "Memory leaks, leak hunting tools"
  color: "bfd4f2"
- name: "A-Message-Forwarding"
  color: "bfd4f2"
- name: "A-Message-Pinning"
  color: "bfd4f2"
- name: "A-Message-Previews"
  color: "bfd4f2"
- name: "A-Message-Starring"
  description: "Saving favourite messages for later"
  color: "bfd4f2"
- name: "A-Modules"
  description: "Module system related"
  color: "bfd4f2"
- name: "A-New-Search-Experience"
  description: "The new search dialog available in Labs"
  color: "bfd4f2"
- name: "A-Packaging"
  description: "Packaging, signing, releasing"
  color: "bfd4f2"
- name: "A-Peeking"
  color: "bfd4f2"
- name: "A-Picture-in-Picture"
  color: "bfd4f2"
- name: "A-Power-Levels"
  description: "The permissions that users have in rooms and spaces"
  color: "bfd4f2"
- name: "A-Replies"
  description: "reply"
  color: "bfd4f2"
- name: "A-Session-Mgmt"
  description: "Session / device names, management UI, etc."
  color: "bfd4f2"
- name: "A-Share"
  color: "bfd4f2"
- name: "A-Shortcuts"
  description: "Keyboard shortcuts"
  color: "bfd4f2"
- name: "A-Sliding-Sync"
  description: "Also known as Sync v3 - https://github.com/matrix-org/sliding-sync"
  color: "bfd4f2"
- name: "A-Soft-Logout"
  description: "https://github.com/element-hq/element-web/issues/10224"
  color: "bfd4f2"
- name: "A-Spaces-Settings"
  color: "bfd4f2"
- name: "A-SSO"
  color: "bfd4f2"
- name: "A-Status-Bar"
  description: "Unsent messages warning and 'Connectivity to the server has been lost'"
  color: "bfd4f2"
- name: "A-Storage"
  description: "Storage layer of the app, including IndexedDB, local storage, etc."
  color: "bfd4f2"
- name: "A-Technical-Debt"
  color: "bfd4f2"
- name: "A-Testing"
  description: "Testing, code coverage, etc."
  color: "bfd4f2"
- name: "A-Themes-Custom"
  description: "Custom theme variables or support"
  color: "bfd4f2"
- name: "A-Themes-Official"
  description: "Official themes (light, dark)"
  color: "bfd4f2"
- name: "A-Theming"
  color: "bfd4f2"
- name: "A-Timeline-Jumpy-Scroll"
  description: "Stable timeline dream ✨"
  color: "bfd4f2"
- name: "A-Timesheet-1"
  description: "Log any time spent on this into the A-Timesheet-1 project"
  color: "5319E7"
- name: "A-Toast"
  color: "bfd4f2"
- name: "A-Tooltips"
  description: "Anything related to tooltips"
  color: "bfd4f2"
- name: "A-UI-Customisation"
  description: "UIFeatures etc. for customising entire parts of the UI"
  color: "bfd4f2"
- name: "A-URL-Previews"
  color: "bfd4f2"
- name: "A-User-Menu"
  description: "The top left main menu with the user's name and avatar"
  color: "bfd4f2"
- name: "A-User-Search"
  description: "The start DM or invite to room dialogs (things dealing with `/user_directory/search`)"
  color: "bfd4f2"
- name: "A-Video-Rooms"
  description: "Persistent group calls"
  color: "bfd4f2"
- name: "A-Voice-Messages"
  color: "bfd4f2"
- name: "A-Welcome-Page"
  color: "bfd4f2"
- name: "backport staging"
  description: "Label to automatically backport PR to staging branch"
  color: "B60205"
- name: "Dependencies"
  description: "Pull requests that update a dependency file"
  color: "0366d6"
- name: "Hacktoberfest"
  description: "Issues which are suitable for Hacktoberfest PRs: https://hacktoberfest.digitalocean.com/"
  color: "ff7518"
- name: "P4"
  description: "[OBSOLETE LABEL] Interesting — Not yet scheduled, will accept patches"
  color: "d1e5f0"
- name: "spam"
  color: "B60205"
- name: "Sponsored"
  color: "ffc8f4"
- name: "T-Deprecation"
  description: "A pull request that makes something deprecated"
  color: "98e6ae"
- name: "T-Other"
  description: "Questions, user support, anything else"
  color: "98e6ae"
- name: "Team: App"
  color: "FFA500"
- name: "X-Blocked"
  color: "ff7979"
- name: "X-Cannot-Reproduce"
  color: "ff7979"
- name: "X-Command"
  description: "Created using the !github command"
  color: "ff7979"
- name: "X-Community-Supported-Platform"
  description: "This issue occurs in a platform not directly supported by us, but by a community project elsewhere"
  color: "ff7979"
- name: "X-Upcoming-Release-Blocker"
  description: "This does not affect the current release cycle but will affect the next one"
  color: "e99695"
- name: "Z-Actions"
  color: "ededed"
- name: "Z-Cache-Confusion"
  description: "Related to internal cache (clearing helps / causes the issue)"
  color: "ededed"
- name: "Z-Community-PR"
  description: "Issue is solved by a community member's PR"
  color: "ededed"
- name: "Z-Element-R-Blocker"
  description: "A blocker for enabling Element R by default"
  color: "ededed"
- name: "Z-Experimental"
  color: "ededed"
- name: "Z-Fixed by Element Call"
  description: "Issues which can be closed when we move to Element Call"
  color: "ededed"
- name: "Z-Fixed-By-OIDC"
  description: "Issues which can be closed when we move to OIDC"
  color: "ededed"
- name: "Z-Flaky-Test"
  description: "A test is raising false alarms"
  color: "ededed"
- name: "Z-FOSDEM"
  description: "Issues in chat.fosdem.org"
  color: "ededed"
- name: "Z-Gitter"
  description: "Issues relating to or coming out of the Gitter migration, feature parity, etc"
  color: "ededed"
- name: "Z-Legacy-Crypto"
  description: "Issues affecting the legacy crypto stack"
  color: "EEEEEE"
- name: "Z-Maximised-Widgets"
  color: "ededed"
- name: "Z-Papercuts"
  description: "Visible. Impactful. Predictable to action."
  color: "ededed"
- name: "Z-Power-Users"
  color: "ededed"
- name: "Z-Rageshake"
  description: "Has attached rageshake (not for log submission process)"
  color: "ededed"
- name: "Z-RICE"
  color: "ededed"
- name: "Z-Soft-Crash"
  description: "React soft crash caught by an error boundary"
  color: "ededed"
- name: "Z-Spec-Compliance"
  description: "An area where Element doesn't correctly implement the spec"
  color: "ededed"
- name: "Z-t3chguy"
  color: "ededed"
- name: "Z-Flaky-Test-Disabled"
  description: "The flaking test has been disabled"
  color: "ededed"
