nodeLinker: hoisted
linkWorkspacePackages: true
packages:
    - "."
    - "packages/*"
catalog:
    # typescript
    typescript: 5.9.3
    # react
    react: ^19.0.0
    react-dom: ^19.0.0
    "@types/react": ^19.2.10
    "@types/react-dom": ^19.2.3
