sonar.projectKey=element-web
sonar.organization=element-hq

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8

sonar.sources=.
sonar.tests=apps/web/test,apps/web/playwright,apps/desktop/playwright,packages
sonar.test.inclusions=apps/web/test/*,apps/web/playwright/*,apps/desktop/playwright/*,packages/*/src/**/*.test.*,packages/*/src/test/**/*
sonar.exclusions=apps/web/__mocks__,docs,apps/web/element.io,apps/web/nginx,apps/web/src/vector/modernizr.cjs

sonar.cpd.exclusions=**/src/i18n/strings/*.json
sonar.javascript.lcov.reportPaths=apps/web/coverage/lcov.info,packages/shared-components/coverage/lcov.info
sonar.coverage.exclusions=\
  apps/web/test/**/*,\
  apps/web/playwright/**/*,\
  apps/web/res/**/*,\
  apps/web/scripts/**/*,\
  apps/desktop/scripts/**/*,\
  apps/desktop/playwright/**/*,\
  apps/desktop/hak/**/*,\
  scripts/**/*,\
  apps/web/src/components/views/dialogs/devtools/**/*,\
  apps/web/src/utils/SessionLock.ts,\
  apps/web/src/**/*.d.ts,\
  apps/web/src/vector/mobile_guide/**/*,\
  packages/shared-components/src/test/**/*,\
  packages/shared-components/src/**/*.stories.tsx,\
  packages/playwright-common/**/*,\
  **/*.config.ts
sonar.testExecutionReportPaths=apps/web/coverage/jest-sonar-report.xml
