name: SonarQube
on:
    workflow_run:
        workflows: ["Tests"]
        types:
            - completed
concurrency:
    group: ${{ github.workflow }}-${{ github.event.workflow_run.head_branch }}
    cancel-in-progress: true
permissions: {}
jobs:
    sonarqube:
        name: 🩻 SonarQube
        if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event != 'merge_group'
        uses: matrix-org/matrix-js-sdk/.github/workflows/sonarcloud.yml@develop
        permissions:
            actions: read
            statuses: write
            id-token: write # sonar
        secrets:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            ELEMENT_BOT_TOKEN: ${{ secrets.ELEMENT_BOT_TOKEN }}
        with:
            sharded: true
