name: Move labelled issues to correct projects

on:
    issues:
        types: [labeled]

permissions: {} # Uses ELEMENT_BOT_TOKEN

jobs:
    call-triage-labelled:
        uses: element-hq/element-web/.github/workflows/triage-labelled.yml@develop # zizmor: ignore[unpinned-uses]
        secrets: inherit # zizmor: ignore[secrets-inherit]
