name: Build element-web
on:
    workflow_call:
        inputs:
            runs-on:
                type: string
                required: false
                description: "The runner to use"
                default: "ubuntu-24.04"
            config-path:
                type: string
                required: false
                description: "Path to the config.json to use. Defaults to element.io/develop/config.json"
                default: "element.io/develop/config.json"
            artifact-name:
                type: string
                required: false
                description: "Name of the artifact to upload"
                default: "webapp"
permissions: {} # No permissions required
jobs:
    build:
        name: Build
        runs-on: ${{ inputs.runs-on }}
        defaults:
            run:
                shell: bash
        steps:
            - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
              with:
                  repository: element-hq/element-web

            - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
              with:
                  # Disable cache on Windows as it is slower than not caching
                  # https://github.com/actions/setup-node/issues/975
                  cache: ${{ runner.os != 'Windows' && 'yarn' || '' }}
                  node-version: "lts/*"

            # Workaround for yarn install timeouts, especially on Windows
            - run: yarn config set network-timeout 300000

            - name: Fetch layered build
              id: layered_build
              env:
                  # This must be set for fetchdep.sh to get the right branch
                  PR_NUMBER: ${{ github.event.pull_request.number }}
                  # tell layered.sh to check out the right sha of the JS-SDK & EW, if they were given one
                  JS_SDK_GITHUB_BASE_REF: ${{ inputs.matrix-js-sdk-sha }}
              run: |
                  scripts/layered.sh
                  JSSDK_SHA=$(git -C matrix-js-sdk rev-parse --short=12 HEAD)
                  VECTOR_SHA=$(git rev-parse --short=12 HEAD)
                  echo "VERSION=$VECTOR_SHA--js-$JSSDK_SHA" >> $GITHUB_OUTPUT

            - name: Copy config
              run: cp "$CONFIG_PATH" config.json
              env:
                  CONFIG_PATH: ${{ inputs.config-path }}

            - name: Build
              env:
                  CI_PACKAGE: true
                  VERSION: "${{ steps.layered_build.outputs.VERSION }}"
              run: |
                  yarn build

            - name: Upload Artifact
              uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
              with:
                  name: ${{ inputs.artifact-name }}
                  path: webapp
                  retention-days: 1
