name: Build and Test
on:
    pull_request: {}
    push:
        branches: [develop, staging, master]
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
permissions: {} # No permissions required
jobs:
    fetch:
        uses: ./.github/workflows/build_prepare.yaml
        permissions:
            contents: read
        with:
            config: ${{ (github.event.pull_request.base.ref || github.ref_name) == 'develop' && 'element.io/nightly' || 'element.io/release' }}
            version: ${{ (github.event.pull_request.base.ref || github.ref_name) == 'develop' && 'develop' || '' }}
            branch-matching: true

    windows:
        needs: fetch
        name: Windows
        uses: ./.github/workflows/build_windows.yaml
        strategy:
            matrix:
                arch: [x64, ia32, arm64]
        with:
            arch: ${{ matrix.arch }}
            blob_report: true

    linux:
        needs: fetch
        name: "Linux (${{ matrix.arch }}) (sqlcipher: ${{ matrix.sqlcipher }})"
        uses: ./.github/workflows/build_linux.yaml
        strategy:
            matrix:
                sqlcipher: [system, static]
                arch: [amd64, arm64]
        with:
            sqlcipher: ${{ matrix.sqlcipher }}
            arch: ${{ matrix.arch }}
            blob_report: true

    macos:
        needs: fetch
        name: macOS
        uses: ./.github/workflows/build_macos.yaml
        with:
            blob_report: true

    tests-done:
        needs: [windows, linux, macos]
        runs-on: ubuntu-24.04
        if: ${{ !cancelled() }}
        steps:
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

            - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4
            - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
              with:
                  cache: "pnpm"
                  node-version: "lts/*"

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Download blob reports from GitHub Actions Artifacts
              uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3 # v8
              with:
                  pattern: blob-report-*
                  path: all-blob-reports
                  merge-multiple: true

            - name: Merge into HTML Report
              run: pnpm playwright merge-reports -c ./playwright.config.ts --reporter=html ./all-blob-reports

            - name: Upload HTML report
              if: always()
              uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7
              with:
                  name: html-report
                  path: playwright-report
                  retention-days: 14

            - if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
              run: exit 1
