name: Dockerbuild
on:
    workflow_dispatch: {}
    push:
        branches: [master, staging, develop]
        paths:
            - "dockerbuild/**"
    pull_request:
concurrency: ${{ github.workflow }}-${{ github.ref_name }}
env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}-dockerbuild
permissions: {}
jobs:
    build:
        name: Docker Build
        runs-on: ubuntu-24.04
        permissions:
            contents: read
            packages: write
        steps:
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
              with:
                  persist-credentials: false

            - name: Set up QEMU
              uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4
              with:
                  install: true

            - name: Build test image
              uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7
              with:
                  file: apps/desktop/dockerbuild/Dockerfile
                  push: false
                  load: true
                  tags: element-desktop-dockerbuild
                  platforms: linux/amd64

            - name: Test image
              run: docker run -v $PWD:/project element-desktop-dockerbuild pnpm install

            - name: Log in to the Container registry
              uses: docker/login-action@c144859092e8e353f3e118b0b329679a62351c3e
              if: github.event_name != 'pull_request'
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Extract metadata for Docker
              id: meta
              if: github.event_name != 'pull_request'
              uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6
              with:
                  images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
                  tags: |
                      type=ref,event=branch
                      type=ref,event=pr

            - name: Build and push Docker image
              if: github.event_name != 'pull_request'
              uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7
              with:
                  file: apps/desktop/dockerbuild/Dockerfile
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
                  platforms: linux/amd64,linux/arm64
