name: Localazy Upload
on:
    workflow_dispatch: {}
    push:
        branches: [develop]
        paths:
            - "apps/web/src/i18n/strings/en_EN.json"
            - "packages/shared-components/src/i18n/strings/en_EN.json"
permissions: {} # No permissions needed
jobs:
    upload:
        environment: Localazy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

            - uses: localazy/upload@27e6b5c0fddf4551596b42226b1c24124335d24a # v1
              with:
                  write_key: ${{ secrets.LOCALAZY_WRITE_KEY }}
