name: Localazy Upload
on:
    workflow_dispatch: {}
    push:
        branches: [develop]
        paths:
            - "apps/web/src/i18n/strings/en_EN.json"
            - "packages/shared-components/src/i18n/strings/en_EN.json"
permissions: {} # No permissions needed
jobs:
    upload:
        environment: Localazy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
              with:
                  persist-credentials: false

            - uses: localazy/upload@27e6b5c0fddf4551596b42226b1c24124335d24a # v1
              with:
                  write_key: ${{ secrets.LOCALAZY_WRITE_KEY }}
