name: Publish npm package
run-name: Publish ${{ inputs.package }}
on:
    workflow_dispatch:
        inputs:
            package:
                description: Which package to release
                required: true
                type: choice
                options:
                    - playwright-common
                    - shared-components
                    - shared-utils
                    - module-api

concurrency: release
jobs:
    publish:
        name: "Publish"
        runs-on: ubuntu-latest
        permissions:
            contents: write
            id-token: write

        steps:
            - name: 🧮 Checkout code
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
              with:
                  persist-credentials: false

            - name: 🔧 Set up pnpm & node environment
              uses: pnpm/setup@fbda4c85fc2e1e08721cd8763afea8f48d60f024 # v3.0.0
              with:
                  cache: true
                  install: true
                  require-lockfile: true

            - name: 🚀 Publish to npm
              working-directory: packages/${{ inputs.package }}
              run: pnpm publish --access public --provenance --publish-branch develop
