name: Build shared component storybook
on:
    merge_group: {}
    pull_request: {}
    workflow_call: {}

permissions: {}

jobs:
    doc:
        name: Build storybook
        runs-on: ubuntu-latest
        steps:
            - name: 🧮 Checkout code
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

            - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4
            - name: 🔧 Pnpm cache
              uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
              with:
                  cache: "pnpm"
                  node-version-file: package.json

            - name: 🔨 Install dependencies
              working-directory: packages/shared-components
              run: "pnpm install --frozen-lockfile"

            - name: 📖 Build Storybook
              working-directory: packages/shared-components
              run: pnpm build:storybook

            - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7
              with:
                  name: shared-components-storybook
                  path: packages/shared-components/storybook-static
                  retention-days: 1
