name: Build shared component storybook
on:
    merge_group: {}
    pull_request: {}
    workflow_call: {}

permissions: {}

jobs:
    doc:
        name: Build storybook
        runs-on: ubuntu-latest
        steps:
            - name: 🧮 Checkout code
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
              with:
                  persist-credentials: false

            - name: 🔧 Set up pnpm & node environment
              uses: pnpm/setup@fbda4c85fc2e1e08721cd8763afea8f48d60f024 # v3.0.0
              with:
                  cache: true
                  install: true
                  require-lockfile: true

            - name: 📖 Build Storybook
              working-directory: packages/shared-components
              run: pnpm build:storybook

            - uses: actions/upload-artifact@cf430e030ddbb5b0abf93d22962f4752f3646cd9 # v7
              with:
                  name: shared-components-storybook
                  path: packages/shared-components/storybook-static
                  retention-days: 1
