name: Build shared component storybook
on:
    merge_group: {}
    pull_request: {}
    workflow_call: {}

permissions: {}

jobs:
    doc:
        name: Build storybook
        runs-on: ubuntu-latest
        steps:
            - name: 🧮 Checkout code
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
              with:
                  persist-credentials: false

            - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5
            - name: 🔧 Pnpm cache
              uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
              with:
                  cache: "pnpm"
                  node-version-file: package.json

            - name: 🔨 Install dependencies
              working-directory: packages/shared-components
              run: "pnpm install --frozen-lockfile"

            - name: 📖 Build Storybook
              working-directory: packages/shared-components
              run: pnpm build:storybook

            - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7
              with:
                  name: shared-components-storybook
                  path: packages/shared-components/storybook-static
                  retention-days: 1
