name: GitHub Pages

on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Set up node environment
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          cache: "yarn"
          node-version-file: ".node-version"

      - name: Build
        run: yarn && yarn build:res && yarn run build-storybook

      - name: Deploy
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4
        # If you're changing the branch from develop,
        # also change the `develop` in `refs/heads/develop`
        # below accordingly.
        if: ${{ github.ref == 'refs/heads/develop' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
