name: Move P1 bugs to boards

on:
  issues:
    types: [labeled, unlabeled]

jobs:
  p1_issues_to_team_workboard:
    runs-on: ubuntu-latest
    if: >
        (!contains(github.event.issue.labels.*.name, 'A-E2EE') &&
         !contains(github.event.issue.labels.*.name, 'A-E2EE-Cross-Signing') &&
         !contains(github.event.issue.labels.*.name, 'A-E2EE-Dehydration') &&
         !contains(github.event.issue.labels.*.name, 'A-E2EE-Key-Backup') &&
         !contains(github.event.issue.labels.*.name, 'A-E2EE-SAS-Verification') &&
         !contains(github.event.issue.labels.*.name, 'A-Spaces') &&
         !contains(github.event.issue.labels.*.name, 'A-Spaces-Settings') &&
         !contains(github.event.issue.labels.*.name, 'A-Subspaces')) &&
        (contains(github.event.issue.labels.*.name, 'T-Defect') &&
         contains(github.event.issue.labels.*.name, 'S-Critical') &&
         (contains(github.event.issue.labels.*.name, 'O-Frequent') ||
          contains(github.event.issue.labels.*.name, 'O-Occasional')) ||
         contains(github.event.issue.labels.*.name, 'S-Major') &&
         contains(github.event.issue.labels.*.name, 'O-Frequent') ||
         contains(github.event.issue.labels.*.name, 'A11y') &&
         contains(github.event.issue.labels.*.name, 'O-Frequent'))
    steps:
      - uses: alex-page/github-project-automation-plus@bb266ff4dde9242060e2d5418e120a133586d488
        with:
          project: Web App Team
          column: P1
          repo-token: ${{ secrets.ELEMENT_BOT_TOKEN }}

  P1_issues_to_crypto_team_workboard:
    runs-on: ubuntu-latest
    if: >
        contains(github.event.issue.labels.*.name, 'Z-UISI') ||
        (contains(github.event.issue.labels.*.name, 'A-E2EE') ||
         contains(github.event.issue.labels.*.name, 'A-E2EE-Cross-Signing') ||
         contains(github.event.issue.labels.*.name, 'A-E2EE-Dehydration') ||
         contains(github.event.issue.labels.*.name, 'A-E2EE-Key-Backup') ||
         contains(github.event.issue.labels.*.name, 'A-E2EE-SAS-Verification')) &&
        (contains(github.event.issue.labels.*.name, 'T-Defect') &&
         contains(github.event.issue.labels.*.name, 'S-Critical') &&
         (contains(github.event.issue.labels.*.name, 'O-Frequent') ||
          contains(github.event.issue.labels.*.name, 'O-Occasional')) ||
         contains(github.event.issue.labels.*.name, 'S-Major') &&
         contains(github.event.issue.labels.*.name, 'O-Frequent') ||
         contains(github.event.issue.labels.*.name, 'A11y') &&
         contains(github.event.issue.labels.*.name, 'O-Frequent'))
    steps:
      - uses: alex-page/github-project-automation-plus@bb266ff4dde9242060e2d5418e120a133586d488
        with:
          project: Crypto Team
          column: Ready
          repo-token: ${{ secrets.ELEMENT_BOT_TOKEN }}
