# Re-fetches the Jitsi SDK and opens a PR to update it if it's different from what's in the repository
name: Update Jitsi
on:
    workflow_dispatch: {}
    schedule:
        - cron: "0 3 * * 0" # 3am every Sunday
permissions: {} # We use ELEMENT_BOT_TOKEN instead
jobs:
    update:
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
              with:
                  persist-credentials: false

            - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
            - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
              with:
                  cache: "pnpm"
                  node-version: "lts/*"

            - name: Install Deps
              run: "pnpm install --frozen-lockfile"

            - name: Fetch Jitsi
              working-directory: apps/web
              run: "pnpm vendor:jitsi"

            - name: Create Pull Request
              uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8
              with:
                  token: ${{ secrets.ELEMENT_BOT_TOKEN }}
                  branch: actions/jitsi-update
                  delete-branch: true
                  title: Jitsi Update
                  labels: |
                      T-Task
